site_name: Vertebrate Breed Ontology
theme: readthedocs
nav:
  - Getting started: index.md
  - VBO general information:
      - VBO general information: general/general.md
      - VBO MIRO information: general/MIRO.md
      - VBO Contributors: general/contributors.md
      - VBO Users and Use cases: general/users.md
      - Sources for Livestock Breeds: general/sources-livestock.md
      - Sources for Cat Breeds: general/sources-cat.md
      - Sources for Dog Breeds: general/sources-dog.md
  - Ontology Modeling:
      - VBO Classification: ontologymodeling/classification.md
      - VBO term Metadata: ontologymodeling/metadata.md
      - Label and Naming Conventions: ontologymodeling/term-labels-naming-conventions.md  
      - Axioms in VBO: ontologymodeling/axioms.md  
      - Database Cross-References: ontologymodeling/xref.md  
      - Term merge and obsolete: ontologymodeling/merge-obsolete.md        
  - VBO Developer Docs:
      - Components: VBO-editor-documents/components.md
      - Release process: VBO-editor-documents/release.md
      - Merging/obsoleting classes: VBO-editor-documents/merge_obsolete_editor.md      
  - How-to guides:
      - Standard ODK workflows:
          - Overview: odk-workflows/index.md
          - Editors Workflow: odk-workflows/EditorsWorkflow.md
          - Release Workflow: odk-workflows/ReleaseWorkflow.md
          - Manage your ODK Repository: odk-workflows/RepoManagement.md
          - Setting up Docker for ODK: odk-workflows/SettingUpDockerForODK.md
          - Imports management: odk-workflows/UpdateImports.md
          - Managing the documentation: odk-workflows/ManageDocumentation.md
          - Continuous Integration: odk-workflows/ContinuousIntegration.md
          - Your ODK Repository Overview: odk-workflows/RepositoryFileStructure.md
      - Contribute: contributing.md
      - Use VBO for data annotation: howto/howtouse.md
  - Cite: cite.md
  - FAQ: FAQ.md
  - History: history.md