name: Initial matching of VBO to DADIS
on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * *'
jobs:
  dadis:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.4.3
    strategy:
      max-parallel: 1
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: work around permission issue
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Match VBO transboundary entries
        run: cd src/ontology/ && make ROBOT_ENV='ROBOT_JAVA_ARGS=-Xmx6G' GITHUB_ACTION=true IMP=false MIR=false dadis-transboundary-sync
        env:
          DADIS_API_KEY: ${{ secrets.DADIS_API_KEY }}
      - name: Match VBO breed-country entries
        run: cd src/ontology/ && make ROBOT_ENV='ROBOT_JAVA_ARGS=-Xmx6G' GITHUB_ACTION=true IMP=false MIR=false dadis-local-sync
        env:
          DADIS_API_KEY: ${{ secrets.DADIS_API_KEY }}
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update local breed file'
          add: 'src/ontology/components/dadisbreedcountry.tsv'

